s3:
  # Auto discover buckets the account has permission to list
  discover: false
  # List of buckets to include
  include:
  - cloudexfil
  # List of buckets to exclude
  exclude: []
  # Maximum size of file to download in bytes (0 if no limit)
  size_limit: 1048576 # 1 Mb
  # Only download files from these storage classes (null for any)
  storage_class:
  - STANDARD
  - REDUCED_REDUNDANCY
  - STANDARD_IA
  - ONEZONE_IA
  - INTELLIGENT_TIERING
  # Time to wait between downloads in millisec
  download_gap: 0
